### PR TITLE
fixed initial _previous_data

### PR DESCRIPTION
**Pull request by ckarrie**
added missing "sum_rx" and "sum_tx" keys thats will be set in _update_current_data

### CODE REVIEW

**Comment by ckarrie** [comment]
**Previous Exception:**

- added `print(self._previous_data)` for debugging

```python
>>> data = sw.get_switch_infos()
self._previous_data {'traffic_tx': [0, 0, 0, 0, 0, 0, 0, 0], 'traffic_rx': [0, 0, 0, 0, 0, 0, 0, 0], 'crc_errors': [0, 0, 0, 0, 0, 0, 0, 0], 'speed_io': [0, 0, 0, 0, 0, 0, 0, 0]}
self._previous_data {'traffic_tx': [0, 0, 0, 0, 0, 0, 0, 0], 'traffic_rx': [0, 0, 0, 0, 0, 0, 0, 0], 'crc_errors': [0, 0, 0, 0, 0, 0, 0, 0], 'speed_io': [0, 0, 0, 0, 0, 0, 0, 0]}
self._previous_data {'traffic_tx': [0, 0, 0, 0, 0, 0, 0, 0], 'traffic_rx': [0, 0, 0, 0, 0, 0, 0, 0], 'crc_errors': [0, 0, 0, 0, 0, 0, 0, 0], 'speed_io': [0, 0, 0, 0, 0, 0, 0, 0]}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/christian/workspace/venvs/pyng/lib/python3.11/site-packages/py_netgear_plus/__init__.py", line 669, in get_switch_infos
    self._update_current_data(current_data, switch_data, sample_time)
  File "/home/christian/workspace/venvs/pyng/lib/python3.11/site-packages/py_netgear_plus/__init__.py", line 807, in _update_current_data
    current_data[f"port_{port_number}_{key}"] = self._previous_data[
                                                ^^^^^^^^^^^^^^^^^^^^
KeyError: 'sum_rx'
```

After fix:

```python
>>> print(data)

{'switch_ip': '192.168.178.5',
 'switch_name': 'GS108Ev3-safe',
 'switch_bootloader': 'V0.00.00',
 'switch_firmware': 'V2.06.24GR',
 'switch_serial_number': '3UXXXXXXF0',
 'port_1_status': 'off',
 'port_1_modus_speed': True,
 'port_1_connection_speed': 0,
 'port_2_status': 'on',
 'port_2_modus_speed': True,
 'port_2_connection_speed': 1000,
 'port_3_status': 'on',
 'port_3_modus_speed': True,
 'port_3_connection_speed': 1000,
 'port_4_status': 'off',
 'port_4_modus_speed': True,
 'port_4_connection_speed': 0,
 'port_5_status': 'on',
 'port_5_modus_speed': True,
 'port_5_connection_speed': 1000,
 'port_6_status': 'on',
 'port_6_modus_speed': True,
 'port_6_connection_speed': 100,
 'port_7_status': 'on',
 'port_7_modus_speed': True,
 'port_7_connection_speed': 1000,
 'port_8_status': 'off',
 'port_8_modus_speed': True,
 'port_8_connection_speed': 0,
 'response_time_s': 2.3,
 'port_1_traffic_rx_mbytes': 0.0,
 'port_1_traffic_tx_mbytes': 0.0,
 'port_1_speed_rx_mbytes': 0.0,
 'port_1_speed_tx_mbytes': 0.0,
 'port_1_speed_io_mbytes': 0.0,
 'port_1_sum_rx_mbytes': 0.0,
 'port_1_sum_tx_mbytes': 0.0,
 'port_2_traffic_rx_mbytes': 67.1,
 'port_2_traffic_tx_mbytes': 379.8,
 'port_2_speed_rx_mbytes': 29.13,
 'port_2_speed_tx_mbytes': 164.86,
 'port_2_speed_io_mbytes': 193.99,
 'port_2_sum_rx_mbytes': 67.1,
 'port_2_sum_tx_mbytes': 379.8,
 'port_3_traffic_rx_mbytes': 106.19,
 'port_3_traffic_tx_mbytes': 33.17,
 'port_3_speed_rx_mbytes': 46.09,
 'port_3_speed_tx_mbytes': 14.4,
 'port_3_speed_io_mbytes': 60.49,
 'port_3_sum_rx_mbytes': 106.19,
 'port_3_sum_tx_mbytes': 33.17,
 'port_4_traffic_rx_mbytes': 0.0,
 'port_4_traffic_tx_mbytes': 0.0,
 'port_4_speed_rx_mbytes': 0.0,
 'port_4_speed_tx_mbytes': 0.0,
 'port_4_speed_io_mbytes': 0.0,
 'port_4_sum_rx_mbytes': 0.0,
 'port_4_sum_tx_mbytes': 0.0,
 'port_5_traffic_rx_mbytes': 0.0,
 'port_5_traffic_tx_mbytes': 4.22,
 'port_5_speed_rx_mbytes': 0.0,
 'port_5_speed_tx_mbytes': 1.83,
 'port_5_speed_io_mbytes': 1.83,
 'port_5_sum_rx_mbytes': 0.0,
 'port_5_sum_tx_mbytes': 4.22,
 'port_6_traffic_rx_mbytes': 0.36,
 'port_6_traffic_tx_mbytes': 4.11,
 'port_6_speed_rx_mbytes': 0.16,
 'port_6_speed_tx_mbytes': 1.79,
 'port_6_speed_io_mbytes': 1.94,
 'port_6_sum_rx_mbytes': 0.36,
 'port_6_sum_tx_mbytes': 4.11,
 'port_7_traffic_rx_mbytes': 406.04,
 'port_7_traffic_tx_mbytes': 171.21,
 'port_7_speed_rx_mbytes': 176.25,
 'port_7_speed_tx_mbytes': 74.32,
 'port_7_speed_io_mbytes': 250.57,
 'port_7_sum_rx_mbytes': 406.04,
 'port_7_sum_tx_mbytes': 171.21,
 'port_8_traffic_rx_mbytes': 0.0,
 'port_8_traffic_tx_mbytes': 0.0,
 'port_8_speed_rx_mbytes': 0.0,
 'port_8_speed_tx_mbytes': 0.0,
 'port_8_speed_io_mbytes': 0.0,
 'port_8_sum_rx_mbytes': 0.0,
 'port_8_sum_tx_mbytes': 0.0,
 'sum_port_traffic_rx': 579.68,
 'sum_port_traffic_tx': 592.51,
 'sum_port_speed_rx': 251.63,
 'sum_port_speed_tx': 257.2,
 'sum_port_speed_io': 508.83,
 'port_8_crc_errors': 0,
 'sum_port_crc_errors': 0}
```

**Comment by ckarrie** [comment]
`sum_rx` and `sum_tx` are generated in the line [`keys = ["sum_rx", "sum_tx", "speed_io"]`](https://github.com/foxey/py-netgear-plus/blob/main/src/py_netgear_plus/__init__.py#L802), maybe we can get rid of this and reword the `current_data` / `_previous_data` structure.

**Comment by foxey** [comment]
Thanks! I'll make you contributor on the repo, so you can contribute more efficiently.

**Comment by foxey** [comment]
@ckarrie sum_r/tx and traffic_r/tx are not redundant (only in the first call). In subsequent calls, trafficr/tx only contains the traffic difference since the previous call.

P.S. I agree that we should refactor the current_data / _previous_data structure. Make it cleaner, but also remove the spike resulting from the first sample of traffic_r/tx being equal to sum_r/tx.

**Comment by ckarrie** [comment]
> @ckarrie sum_r/tx and traffic_r/tx are not redundant (only in the first call). In subsequent calls, trafficr/tx only contains the traffic difference since the previous call.

Shame on me, you're absolutely right. 

> P.S. I agree that we should refactor the current_data / _previous_data structure. Make it cleaner, but also remove the spike resulting from the first sample of traffic_r/tx being equal to sum_r/tx.

Good plan!

**Pull request merged**
